# Minimal Slack API Kubernetes Configuration
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: penny-wise
  labels:
    name: penny-wise

---
# Deployment (minimal configuration)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: penny-wise
  namespace: penny-wise
  labels:
    app: penny-wise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penny-wise
  template:
    metadata:
      labels:
        app: penny-wise
    spec:
      containers:
      - name: penny-wise
        image: sarindockerhub/penny-wise:latest  # Update with your actual Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # Only include environment variables your app actually needs
        # env:
        # - name: PORT
        #   value: "8181"
        # Add your specific environment variables here
        resources:
          requests:
            memory: "64Mi"   # Very minimal for basic apps
            cpu: "50m"
          limits:
            memory: "128Mi"  # Can increase if needed
            cpu: "100m"
        # Basic health check using the port
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: penny-wise-service
  namespace: penny-wise
spec:
  selector:
    app: penny-wise
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP  # Simple external access
