# Minimal Slack API Kubernetes Configuration
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: penny-wise
  labels:
    name: penny-wise

---
# Deployment (minimal configuration)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: penny-wise
  namespace: penny-wise
  labels:
    app: penny-wise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penny-wise
  template:
    metadata:
      labels:
        app: penny-wise
    spec:
      containers:
      - name: penny-wise
        image: sarindockerhub/penny-wise:latest  # Update with your actual Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # Only include environment variables your app actually needs
        # env:
        # - name: PORT
        #   value: "8181"
        # Add your specific environment variables here
        resources:
          requests:
            memory: "64Mi"   # Very minimal for basic apps
            cpu: "50m"
          limits:
            memory: "128Mi"  # Can increase if needed
            cpu: "100m"
        # Basic health check using the port
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
#ingress
apiVersion: v1
kind: Service
metadata:
  name: penny-wise-service
  namespace: penny-wise
spec:
  selector:
    app: penny-wise
  ports:
  - port: 3000        # Service port (TCP)
    targetPort: 3000  # Container port
    protocol: TCP
  type: LoadBalancer     # Internal cluster access only
---  
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: penny-wise-ingress
  namespace: penny-wise
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: penny-wise.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: penny-wise-service
            port:
              number: 3000  
